.Dd October 10, 2018
.Dt TORUS 7
.Os "Causal Agency"
.
.Sh NAME
.Nm torus
.Nd welcome to ascii.town!
.
.Sh DESCRIPTION
This software targets
.Fx
and Darwin.
.
.Pp
.Bl -tag -width "snapshot.sh" -compact
.It Pa torus.h
Shared structures and message protocol.
.
.It Pa server.c
Maps
.Pa torus.dat
and listens on
.Pa torus.sock .
.
.It Pa client.c
.Xr curses 3
client.
.
.It Pa help.h
Tile data for help page.
.
.It Pa image.c
Renders PNGs of tiles.
.
.It Pa meta.c
Exports metadata from data file to CSV.
.
.It Pa merge.c
Interactively merges two data files.
.
.It Pa snapshot.sh
Snapshots data file, appropriate for cron.
.El
.
.Pp
.Bl -tag -width "default8x16.psfu" -compact
.It Pa sshd_config
Anonymous login to
.Xr chroot 8 Ap d client.
.
.It Pa index.html
Friendly directions.
.
.It Pa default8x16.psfu
Bitmap font from
.Lk http://kbd-project.org kbd .
.El
